name: 'Ejecutar Docker'
on: push
jobs:
  saludar:
    runs-on: ubuntu-latest
    name: 'Tarea para saludarme'
    steps:
      - name: 'Ejecutar la accion del docher'
        id: hola
        uses: Docker-MG/accion@v1
        whith:
          quien: 'Lucho'
      - name: 'Mostrar la hora obtenida'
        run: echo "La hora obtenida fue ${{ steps.hola.outputs.hota }}"
