name: 'Ejecutar Docker'
on: push
jobs:
  saludar:
    runs-on: ubuntu-latest
    name: 'Tarea para saludarme'
    steps:
      - name: 'Ejecutar la accion del docher'
        id: hola
        uses: dzamoraperez/Docker-MG@main
        with:
          quien: 'Lucho'
      - name: 'Mostrar la hora obtenida'
        run: echo "La hora obtenida fue ${{ steps.hola.outputs.hota }}"
